name: Build APK

on: 
  push:
    branches: [ main ]  # You can adjust the trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Check out code

      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Adjust Java version if required
          distribution: 'temurin'  # Or other Java distributions 

      - name: Build APK
        run: ./gradlew assembleRelease  # Or assembleDebug for debug build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk  # Adjust the name
          path: app/build/outputs/apk/release/app-release.apk  
