name: Build Launcher3 APK

on: 
  push:
    branches: [ fourteen ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Updated to latest
      - name: Set up JDK 
        uses: actions/setup-java@v3 # Updated to latest
        with:
          java-version: '11'  
          distribution: 'temurin'

      # ... (Rest of your steps) 
