name: Build Launcher3 APK

on: 
  push:
    branches: [ fourteen ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '11'  
          distribution: 'temurin'

      - name: Install repo  # Step for installing the repo tool
        run: |
          wget https://storage.googleapis.com/git-repo-downloads/repo -O /usr/local/bin/repo 
          chmod a+x /usr/local/bin/repo

      - name: Sync and Build Launcher3 
        run: |
          ./repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc) # Sync might need customization
          source build/envsetup.sh
          lunch aosp_arm64-eng  # Or a relevant target name
          make -j$(nproc) Launcher3

      # ...
